version: '3.7'

services:
  db:
    image: bloodshop/petshopdb:1.0
    restart: always
    ports:
      - '1401:1433'
    environment:
        SA_PASSWORD: Pa$$w0rd2019
        ACCEPT_EULA: Y
        MSSQL_PID: Developer
  app:
    depends_on:
      - db
    image: bloodshop/petshopapp:1.0
    ports: 
        - "3000:80" 
        - "3001:433"
    networks: 
       - db-bridge
    restart: always